#!/usr/bin/env python

import argparse

from config import MtgSpoilerConfig
from database import Database
from manager import Manager
from models import Card, Set
from scryfall import ScryfallClient
from slackclient import SlackClient


def get_manager() -> Manager:
    config = MtgSpoilerConfig.from_env()
    api = ScryfallClient()
    db = Database(config.db_uri)
    slack = SlackClient(config.slack_webhook_url, config.slack_channel)
    return Manager(config, db, api, slack)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('action', help='One of: refresh, watch, unwatch')
    parser.add_argument('--sets', action='store_true', help='For refresh, also update set information')
    parser.add_argument('arguments', metavar='SET', type=str, nargs='*', help='Individual sets to watch/unwatch')
    return parser.parse_args()

if __name__ == '__main__':
    args = parse_args()
    manager = get_manager().handle(args.action, args.arguments, sets=args.sets)
